
services:
  backend:
    build:
      context: app
      dockerfile: Dockerfile.prod
#    command: /app/app_entrypoint.prod.sh
    env_file:
      - .env.prod
    restart: always
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    build:
      context: app
      dockerfile: Dockerfile.prod
    command: python /app/run_bot.py
    env_file:
      - .env.prod
    restart: always
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      backend:
        condition: service_started

  database:
    image: postgres:16.2-alpine3.18
    env_file: .env.prod
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 4gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  nginx:
    build: nginx
    env_file: .env.prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - certs:/etc/letsencrypt
    depends_on:
      - backend
      - frontend2

#  frontend:
#    build:
#      context: ../web-menu/
#      dockerfile: Dockerfile
#    restart: always
#    expose:
#      - 3000
#    depends_on:
#      - backend
#    volumes:
#      - static_volume:/frontend_static

  frontend2:
    build:
      context: ../imenu-nextjs/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3001
    depends_on:
      - backend
    volumes:
      - static_volume:/frontend_static

volumes:
  database-storage:
  redis_data:
  static_volume:
  media_volume:
  certs:
