# Generated by Django 5.1 on 2025-01-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID точки')),
                ('name', models.CharField(max_length=100, verbose_name='Название заведения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес заведения')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='venues.venue')),
            ],
        ),
    ]
