# Generated by Django 5.1 on 2025-01-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID стола')),
                ('table_num', models.IntegerField()),
                ('table_title', models.CharField(max_length=255)),
                ('spot_id', models.IntegerField()),
                ('table_shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round')], max_length=50)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venues.venue')),
            ],
        ),
    ]
