# Generated by Django 5.1 on 2025-01-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_num',
            field=models.CharField(max_length=255),
        ),
    ]
