# Generated by Django 5.1 on 2025-01-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_table_table_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_shape',
            field=models.CharField(choices=[('square', 'Square'), ('circle', 'Circle')], max_length=50),
        ),
    ]
