# Generated by Django 5.1 on 2025-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_remove_table_spot_id_table_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешний ID точки'),
        ),
        migrations.AlterField(
            model_name='table',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешний ID стола'),
        ),
    ]
