# Generated by Django 5.1 on 2025-01-21 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_alter_spot_external_id_alter_table_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterField(
            model_name='spot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='venues.venue', verbose_name='Заведение'),
        ),
        migrations.AlterField(
            model_name='table',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venues.spot', verbose_name='Точка заведения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_num',
            field=models.CharField(max_length=255, verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_shape',
            field=models.CharField(choices=[('square', 'Квадратный'), ('circle', 'Круглый')], max_length=50, verbose_name='Форма стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_title',
            field=models.CharField(max_length=255, verbose_name='Название стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venues.venue', verbose_name='Заведение'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='account_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер аккаунта'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='next_pay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей оплаты'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта владельца'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_id',
            field=models.PositiveIntegerField(verbose_name='ID владельца'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон владельца'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='pos_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.possystem', verbose_name='POS система'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tariff_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ тарифа'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tariff_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена тарифа'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
