# Generated by Django 5.1 on 2025-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_table_options_alter_venue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tip_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент за обслуживание'),
        ),
    ]
