# Generated by Django 5.1 on 2025-02-15 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_alter_possystem_options_alter_spot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': 'Точка заведения', 'verbose_name_plural': 'Точки заведения'},
        ),
        migrations.AlterField(
            model_name='table',
            name='table_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название стола'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
