# Generated by Django 5.1 on 2025-02-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_spot_options_alter_table_table_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='user',
        ),
    ]
