# Generated by Django 5.1 on 2025-02-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_remove_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='color_theme',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#1E90FF', 'Dodger Blue'), ('#32CD32', 'Lime Green'), ('#FFD700', 'Gold')], default='#FFFFFF', max_length=7),
        ),
    ]
