# Generated by Django 5.1 on 2025-02-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_venue_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_logo', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='venue',
            name='schedule',
            field=models.CharField(default='09:00-18:00', help_text='Введите график работы, например: 09:00-18:00', max_length=255, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='color_theme',
            field=models.CharField(choices=[('#008B68', 'Темно-зеленый'), ('#FFB200', 'Янтарный'), ('#F80101', 'Алый'), ('#FF4800', 'Оранжевый'), ('#00BBFF', 'Голубой'), ('#0717FF', 'Синий'), ('#AF00A3', 'Розовый')], default='#008B68', max_length=7),
        ),
    ]
