# Generated by Django 5.1 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_venue_logo_venue_schedule_alter_venue_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Название ссылки'),
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Название ссылки'),
            preserve_default=False,
        ),
    ]
