# Generated by Django 5.1 on 2025-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_spot_slug_venue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Название ссылки'),
        ),
    ]
