# Generated by Django 5.1 on 2025-03-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_alter_venue_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название принтера')),
                ('printer_id', models.CharField(max_length=255, verbose_name='ID принтера')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_printers', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Принтер для чека',
                'verbose_name_plural': 'Принтеры для чека',
            },
        ),
    ]
