# Generated by Django 5.1 on 2025-03-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_venue_telegram_bot_token_venue_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='telegram_chat_id',
        ),
    ]
