# Generated by Django 5.1 on 2025-03-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_remove_venue_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptPrinter',
        ),
    ]
