# Generated by Django 5.1 on 2025-04-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_delete_receiptprinter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='tip_amount',
            new_name='service_fee_percent',
        ),
    ]
