# Generated by Django 5.1 on 2025-04-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_rename_tip_amount_venue_service_fee_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('banner', models.ImageField(max_length=255, upload_to='', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('draft', 'Черновик')], default='draft', max_length=10, verbose_name='Статус')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
            },
        ),
    ]
