# Generated by Django 5.1 on 2025-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to='banners/%Y/%m/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner-images/%Y/%m/', verbose_name='Картинка'),
        ),
    ]
