# Generated by Django 5.1 on 2025-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_alter_banner_banner_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
