# Generated by Django 5.1 on 2025-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0025_venue_is_delivery_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен доступа для POS-системы'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер аккаунта'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID владельца'),
        ),
    ]
