# Generated by Django 5.1 on 2025-04-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0026_alter_venue_access_token_alter_venue_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='slug',
        ),
    ]
