# Generated by Django 5.1 on 2025-05-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0028_workinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='schedule',
        ),
        migrations.AddField(
            model_name='venue',
            name='work_end',
            field=models.TimeField(default='18:00', help_text='Введите время окончания (например, 18:00)', verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='venue',
            name='work_start',
            field=models.TimeField(default='09:00', help_text='Введите время начала (например, 09:00)', verbose_name='Начало рабочего дня'),
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
