# Generated by Django 5.1 on 2025-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0029_remove_venue_schedule_venue_work_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('#008B68', 'Темно-зеленый'), ('#FFB200', 'Янтарный'), ('#F80101', 'Алый'), ('#FF4800', 'Оранжевый'), ('#00BBFF', 'Голубой'), ('#0717FF', 'Синий'), ('#AF00A3', 'Розовый')], default='#008B68', max_length=7, verbose_name='Тема'),
        ),
    ]
