# Generated by Django 5.1 on 2025-08-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0031_alter_venue_color_theme_alter_venue_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='default_delivery_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_venue', to='venues.spot', verbose_name='Точка доставки по умолчанию'),
        ),
    ]
