# Generated by Django 5.1 on 2025-08-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0033_alter_venue_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('#008B68', 'Темно-зеленый'), ('#FFB200', 'Янтарный'), ('#F80101', 'Алый'), ('#FF4800', 'Оранжевый'), ('#00BBFF', 'Голубой'), ('#0717FF', 'Синий'), ('#AF00A3', 'Розовый'), ('#000000', 'Черный'), ('#00BFB2', 'Бирюзовый')], default='#008B68', max_length=7, verbose_name='Тема'),
        ),
    ]
