# Generated by Django 5.1 on 2025-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0034_alter_venue_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
    ]
