# Generated by Django 5.1 on 2025-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0035_spot_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='delivery_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки (фиксированная)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='delivery_free_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бесплатная доставка от суммы'),
        ),
    ]
