# Generated by Django 5.1 on 2025-09-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0036_venue_delivery_fixed_fee_venue_delivery_free_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='bonus_accrual_percent',
            field=models.PositiveIntegerField(default=0, help_text='Сколько процентов от суммы заказа будет начисляться бонусами (например: 5 = 5%)', verbose_name='Процент начисления бонусов'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_bonus_system_enabled',
            field=models.BooleanField(default=False, verbose_name='Бонусная система включена'),
        ),
    ]
