# Generated by Django 5.1 on 2025-09-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0037_venue_bonus_accrual_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='work_start',
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('is_24h', models.BooleanField(default=False, verbose_name='Круглосуточно')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='venues.venue')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ('day_of_week',),
                'unique_together': {('venue', 'day_of_week')},
            },
        ),
    ]
