# Generated by Django 5.1 on 2025-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0038_remove_venue_work_end_remove_venue_work_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='terms',
            field=models.TextField(blank=True, help_text='Здесь можно указать правила, условия обслуживания, доставки и т.д.', null=True, verbose_name='Условия заведения'),
        ),
    ]
