# Generated by Django 5.1 on 2025-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0039_venue_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, help_text='Общая информация о заведении', null=True, verbose_name='Описание заведения'),
        ),
    ]
