# Generated by Django 5.1 on 2025-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0040_venue_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='service_fee_percent',
        ),
        migrations.AddField(
            model_name='venue',
            name='delivery_service_fee_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент за обслуживание (доставка)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='dinein_service_fee_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент за обслуживание (на месте)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='takeout_service_fee_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент за обслуживание (самовывоз)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bonus_accrual_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент начисления бонусов'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание заведения'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия заведения'),
        ),
    ]
