# Generated by Django 5.1 on 2025-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0041_remove_venue_service_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Telegram-группы'),
        ),
    ]
