# Generated by Django 5.1 on 2025-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0042_spot_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='wifi_text',
            field=models.TextField(blank=True, help_text='Описание Wi‑Fi подключения, инструкции или промо‑сообщение', null=True, verbose_name='Текст Wi‑Fi блока'),
        ),
        migrations.AddField(
            model_name='spot',
            name='wifi_url',
            field=models.URLField(blank=True, help_text="URL-кнопка 'Подключиться'", null=True, verbose_name='Ссылка для подключения Wi‑Fi'),
        ),
    ]
