# Generated by Django 5.1 on 2025-10-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0043_spot_wifi_text_spot_wifi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='ai_generate_prompt',
            field=models.TextField(blank=True, help_text='Описание изображения для AI генерации (если пусто — используется стандартный текст)', null=True, verbose_name='Промпт для генерации изображения'),
        ),
        migrations.AddField(
            model_name='venue',
            name='ai_improve_prompt',
            field=models.TextField(blank=True, help_text='Дополнительное описание, как улучшить текущее изображение (если оставить пустым, используется стандартный текст)', null=True, verbose_name='Промпт для улучшения изображения'),
        ),
    ]
