# Generated by Django 5.1 on 2025-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0044_venue_ai_generate_prompt_venue_ai_improve_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='table_qr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для QR‑кода стола'),
        ),
    ]
