# Generated by Django 5.1 on 2025-10-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0045_venue_table_qr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='table_qr_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст для QR‑кода стола'),
        ),
    ]
