# Generated by Django 5.1 on 2025-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0046_alter_venue_table_qr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='table_qr_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст для QR‑кода стола'),
        ),
        migrations.AddField(
            model_name='venue',
            name='table_qr_text_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст для QR‑кода стола'),
        ),
        migrations.AddField(
            model_name='venue',
            name='table_qr_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст для QR‑кода стола'),
        ),
    ]
