# Generated by Django 5.1 on 2025-11-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0047_venue_table_qr_text_en_venue_table_qr_text_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('unique_visitors', models.JSONField(blank=True, default=list)),
                ('unique_count', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.table')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='venues.venue')),
            ],
            options={
                'unique_together': {('venue', 'table', 'date')},
            },
        ),
    ]
