# Generated by Django 5.1 on 2025-01-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificator',
            old_name='modificator_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modificator',
            old_name='modificator_selfprice',
            new_name='price',
        ),
    ]
