# Generated by Django 5.1 on 2025-01-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_category_level_remove_category_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modificators',
        ),
        migrations.AddField(
            model_name='modificator',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modificators', to='menu.product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
