# Generated by Django 5.1 on 2025-01-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_product_modificators_modificator_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificator',
            old_name='venue',
            new_name='product',
        ),
    ]
