# Generated by Django 5.1 on 2025-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/category/%Y/%m', verbose_name='Фото категории'),
        ),
    ]
