# Generated by Django 5.1 on 2025-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_parent_category_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='visible',
            field=models.JSONField(blank=True, default=list, verbose_name='Видимость категории на точках'),
        ),
    ]
