# Generated by Django 5.1 on 2025-01-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_category_id_alter_category_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
