# Generated by Django 5.1 on 2025-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_external_id_alter_product_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modificator',
            options={'verbose_name': 'Модификатор', 'verbose_name_plural': 'Модификаторы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='modificator',
            name='external_id',
            field=models.CharField(max_length=100, verbose_name='Внешний ID модификатора'),
        ),
        migrations.AlterField(
            model_name='modificator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название модификатора'),
        ),
        migrations.AlterField(
            model_name='modificator',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
