# Generated by Django 5.1 on 2025-01-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_parent_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
    ]
