# Generated by Django 5.1 on 2025-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_product_is_recommended_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытый товар?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='в рекомендациях?'),
        ),
    ]
