# Generated by Django 5.1 on 2025-01-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID категории'),
        ),
    ]
