# Generated by Django 5.1 on 2025-01-27 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_product_hidden_alter_product_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='modificator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modificator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендован?'),
        ),
    ]
