# Generated by Django 5.1 on 2025-01-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_photo_origin',
        ),
    ]
