# Generated by Django 5.1 on 2025-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название атрибута'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
