# Generated by Django 5.1 on 2025-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_product_spot'),
        ('venues', '0010_alter_possystem_options_alter_spot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spot',
        ),
        migrations.AddField(
            model_name='product',
            name='spot',
            field=models.ManyToManyField(related_name='products', to='venues.spot', verbose_name='Точки заведения'),
        ),
    ]
