# Generated by Django 5.1 on 2025-02-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_product_spot_product_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spot',
            new_name='spots',
        ),
    ]
