# Generated by Django 5.1 on 2025-02-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_rename_spot_product_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pos_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pos_system',
        ),
    ]
