# Generated by Django 5.1 on 2025-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_remove_category_pos_system_remove_product_pos_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='modificator',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модификатора'),
        ),
        migrations.AddField(
            model_name='modificator',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модификатора'),
        ),
        migrations.AddField(
            model_name='modificator',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название модификатора'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
    ]
