# Generated by Django 5.1 on 2025-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificator',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
