# Generated by Django 5.1 on 2025-07-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_modificator_price_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/category/%Y/%m', verbose_name='Оригинальное фото категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/products/%Y/%m', verbose_name='Оригинальное фото товара'),
        ),
    ]
