# Generated by Django 5.1 on 2025-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_category_category_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_hidden',
            field=models.BooleanField(default=False, help_text='При скрытии категории будут скрыты все товары в ней', verbose_name='Скрыт?'),
        ),
    ]
