# Generated by Django 5.1 on 2025-09-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_alter_category_category_hidden'),
        ('venues', '0040_venue_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='menu_produc_product_3eda49_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['venue', 'hidden'], name='menu_produc_venue_i_99cf41_idx'),
        ),
    ]
