# Generated by Django 5.1 on 2025-10-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_product_menu_produc_product_3eda49_idx_and_more'),
        ('venues', '0042_spot_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu/section/%Y/%m', verbose_name='Фото')),
                ('categories', models.ManyToManyField(related_name='sections', to='menu.category', verbose_name=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Базовая модель',
                'verbose_name_plural': 'Базовые модели',
                'abstract': False,
            },
        ),
    ]
