# Generated by Django 5.1 on 2025-10-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_section'),
        ('venues', '0042_spot_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(related_name='sections', to='menu.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='MainButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('button_type', models.CharField(choices=[('section', 'Раздел'), ('category', 'Категория')], max_length=20)),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_buttons', to='venues.venue')),
            ],
        ),
    ]
