# Generated by Django 5.1 on 2025-10-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_section_categories_mainbutton'),
        ('venues', '0042_spot_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbutton',
            options={
                'ordering': ['order'],
                'verbose_name': 'Главная кнопка',
                'verbose_name_plural': 'Главные кнопки',
            },
        ),
        migrations.AddField(
            model_name='mainbutton',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='main_buttons',
                to='menu.category',
                verbose_name='Связанная категория',
            ),
        ),
        migrations.AddField(
            model_name='mainbutton',
            name='order',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Кнопка 1'), (2, 'Кнопка 2'), (3, 'Кнопка 3'), (4, 'Кнопка 4'), (5, 'Кнопка 5')],
                help_text='Номер кнопки от 1 до 5',
                verbose_name='Порядок кнопки',
            ),
        ),
        migrations.AddField(
            model_name='mainbutton',
            name='section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='main_buttons',
                to='menu.section',
                verbose_name='Связанный раздел',
            ),
        ),
        migrations.RemoveField(name='link_id', model_name='mainbutton'),
        migrations.RemoveField(name='title', model_name='mainbutton'),

        # <--- ЭТО ставим ПОСЛЕ добавления поля order:
        migrations.AlterUniqueTogether(
            name='mainbutton',
            unique_together={('venue', 'order')},
        ),
    ]
