# Generated by Django 5.1 on 2025-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_mainbutton_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия категории', max_length=255, null=True, verbose_name='URL слаг'),
        ),
        migrations.AlterField(
            model_name='mainbutton',
            name='button_type',
            field=models.CharField(choices=[('section', 'Раздел'), ('category', 'Категория')], max_length=20, verbose_name='Тип кнопки'),
        ),
    ]
