# Generated by Django 5.1 on 2025-10-08 13:28

from django.db import migrations
from django.utils.text import slugify
from unidecode import unidecode


def fill_slugs(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')

    for category in Category.objects.all():
        if not category.slug:
            base_slug = slugify(unidecode(category.category_name))
            slug = base_slug
            num = 1
            # Проверяем уникальность
            while Category.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            category.slug = slug
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_category_slug_alter_mainbutton_button_type'),
    ]

    operations = [
        migrations.RunPython(fill_slugs),
    ]
