# Generated by Django 5.1 on 2025-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_fill_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products_many', to='menu.category', verbose_name='Категории'),
        ),
    ]
