# Generated by Django 5.1 on 2025-10-29 16:25

from django.db import migrations

def migrate_category_to_many(apps, schema_editor):
    Product = apps.get_model('menu', 'Product')
    for product in Product.objects.all():
        if product.category_id:  # Если категория была выбрана
            product.categories.add(product.category_id)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_product_categories'),
    ]

    operations = [
        migrations.RunPython(migrate_category_to_many, migrations.RunPython.noop),
    ]
