# Generated by Django 5.1 on 2025-10-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_migrate_category_to_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
