# Generated by Django 5.1 on 2025-11-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='menu.category', verbose_name='Категории'),
        ),
    ]
