# Generated by Django 5.1 on 2025-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее число → выше в списке', verbose_name='Порядок сортировки'),
        ),
    ]
