# Generated by Django 5.1 on 2025-11-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
