# Generated by Django 5.1 on 2025-02-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('venues', '0012_remove_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='venue',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venues.venue', verbose_name='Заведение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
