# Generated by Django 5.1 on 2025-02-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_venue_alter_user_role'),
        ('venues', '0012_remove_venue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venues.venue', verbose_name='Заведение'),
        ),
    ]
