# Generated by Django 5.1 on 2025-02-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_venue'),
        ('venues', '0012_remove_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venues.spot', verbose_name='Точка заведения'),
        ),
    ]
