# Generated by Django 5.1 on 2025-03-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
