# Generated by Django 5.1 on 2025-06-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_phoneverification_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
