# Generated by Django 5.1 on 2025-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_balance_user_is_agent_user_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_code',
        ),
    ]
