# Generated by Django 5.1 on 2025-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_balance_remove_user_is_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='is_bonus_verified',
            field=models.BooleanField(default=False),
        ),
    ]
