# Generated by Django 5.1 on 2025-01-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('venues', '0002_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='venues.venue', verbose_name='Заведение'),
            preserve_default=False,
        ),
    ]
