# Generated by Django 5.1 on 2025-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_total_price_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(default=1, max_length=100, verbose_name='Внешний ID онлайн-заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='service_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На месте'), (2, 'Самовывоз'), (3, 'Доставка')], default=1),
        ),
    ]
