# Generated by Django 5.1 on 2025-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='скидка в %'),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за обслуживание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусы'),
        ),
    ]
