# Generated by Django 5.1 on 2025-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_productattribute_name_and_more'),
        ('orders', '0011_orderproduct_created_at_orderproduct_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_attributes',
            field=models.ManyToManyField(blank=True, to='menu.productattribute', verbose_name='Атрибуты Продукта'),
        ),
    ]
