# Generated by Django 5.1 on 2025-02-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderproduct_product_attributes'),
        ('venues', '0014_venue_logo_venue_schedule_alter_venue_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spot',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='venues.spot', verbose_name='Точка заведения'),
            preserve_default=False,
        ),
    ]
