# Generated by Django 5.1 on 2025-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_price',
            field=models.BigIntegerField(default=0, verbose_name='Цена за обслуживание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tips_price',
            field=models.BigIntegerField(default=0, verbose_name='Чаевые'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0, verbose_name='Итоговая цена'),
        ),
    ]
