# Generated by Django 5.1 on 2025-03-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_service_price_alter_order_tips_price_and_more'),
        ('venues', '0020_delete_receiptprinter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название принтера')),
                ('printer_id', models.CharField(max_length=255, verbose_name='ID принтера')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_printers', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Принтер для чека',
                'verbose_name_plural': 'Принтеры для чека',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('order_count', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('payload', models.JSONField(verbose_name='JSON-данные чека')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.order', verbose_name='Заказ')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='venues.venue', verbose_name='Заведение')),
                ('receipt_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='orders.receiptprinter', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
            },
        ),
    ]
