# Generated by Django 5.1 on 2025-04-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_receiptprinter_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="spot",
            field=models.ForeignKey(
                to="venues.Spot",
                on_delete=models.CASCADE,
                related_name="orders",
                null=True,
                blank=True,
                verbose_name="Точка заведения"
            ),
        ),
    ]
