# Generated by Django 5.1 on 2025-04-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_make_spot_nullable'),
        ('venues', '0021_rename_tip_amount_venue_service_fee_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='venues.spot', verbose_name='Точка заведения'),
        ),
    ]
