# Generated by Django 5.1 on 2025-04-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_spot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID онлайн-заказа'),
        ),
    ]
