# Generated by Django 5.1 on 2025-04-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptprinter',
            name='topic',
            field=models.CharField(default=1, max_length=255, verbose_name='Топик'),
            preserve_default=False,
        ),
    ]
