# Generated by Django 5.1 on 2025-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_receiptprinter_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за обслуживание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tips_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чаевые'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
