# Generated by Django 5.1 on 2025-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_discount_alter_order_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за обслуживание (в сомах)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tips_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Чаевые (в сомах)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая цена (в сомах)'),
        ),
    ]
