# Generated by Django 5.1 on 2025-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_service_price_alter_order_tips_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='total_payed_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма платежей'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
    ]
