# Generated by Django 5.1 on 2025-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_client_total_payed_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_tg_bot',
            field=models.BooleanField(default=False, verbose_name='Из телеграмм бота'),
        ),
        migrations.AddField(
            model_name='order',
            name='tg_redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='Редирект url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за обслуживание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tips_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Чаевые'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая цена'),
        ),
    ]
