# Generated by Django 5.1 on 2025-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_is_tg_bot_order_tg_redirect_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tg_redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='Редирект url бота'),
        ),
    ]
