# Generated by Django 5.1 on 2025-05-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_tg_redirect_url'),
        ('venues', '0027_remove_spot_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('venue', 'phone')},
        ),
    ]
