# Generated by Django 5.1 on 2025-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за обслуживание'),
        ),
    ]
