# Generated by Django 5.1 on 2025-05-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_orderproduct_price_and_more'),
        ('venues', '0027_remove_spot_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('bakai', 'Bakai bank')], max_length=50, verbose_name='Сервис')),
                ('name', models.CharField(blank=True, help_text='Название или описание аккаунта', max_length=100, null=True)),
                ('token', models.TextField(help_text='Секретный платёжный токен/API ключ')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Платёжный аккаунт',
                'verbose_name_plural': 'Платёжные аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус оплаты')),
                ('json_data', models.JSONField(blank=True, null=True, verbose_name='Ответ из платежной системы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
