# Generated by Django 5.1 on 2025-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_paymentaccount_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], default='pending', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
