# Generated by Django 5.1 on 2025-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заказ оформлен'), (1, 'Готовим заказ'), (2, 'Заказ готов'), (3, 'Заказ выполнен'), (7, 'Отменён')], default=0, verbose_name='Статус заказа'),
        ),
    ]
