# Generated by Django 5.1 on 2025-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заказ оформлен'), (1, 'Готовим заказ'), (2, 'Заказ готов'), (3, 'Заказ выполнен'), (4, 'Ожидает оплату'), (7, 'Отменён')], default=4, verbose_name='Статус заказа'),
        ),
    ]
