# Generated by Django 5.1 on 2025-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_ref_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_agent',
        ),
    ]
