# Generated by Django 5.1 on 2025-09-07 03:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_order_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите в формате 0 или 996', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
