# Generated by Django 5.1 on 2025-09-07 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_client_phone_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Положительное = начисление, отрицательное = списание', verbose_name='Сумма бонусов')),
                ('operation', models.CharField(choices=[('accrual', 'Начисление'), ('write_off', 'Списание')], max_length=20, verbose_name='Операция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, help_text='Причина начисления или списания', null=True, verbose_name='Описание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='orders.client', verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История бонуса',
                'verbose_name_plural': 'История бонусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
