# Generated by Django 5.1 on 2025-09-07 05:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_bonushistory'),
        ('venues', '0037_venue_bonus_accrual_percent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите в формате 0 или 996', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('venue', 'phone_number')},
        ),
    ]
