# Generated by Django 5.1 on 2025-09-17 14:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_client_unique_together_and_more'),
        ('venues', '0040_venue_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите в формате 0 или 996', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_payed_sum',
        ),
        migrations.RemoveField(
            model_name='client',
            name='venue',
        ),
        migrations.CreateModel(
            name='ClientVenueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('bonus', models.PositiveIntegerField(default=0, verbose_name='Бонусы')),
                ('total_payed_sum', models.PositiveIntegerField(default=0, verbose_name='Общая сумма платежей')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_profiles', to='orders.client', verbose_name='Клиент')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Профиль клиента в заведении',
                'verbose_name_plural': 'Профили клиентов в заведениях',
                'unique_together': {('client', 'venue')},
            },
        ),
    ]
