# Generated by Django 5.1 on 2025-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_client_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bonus',
        ),
    ]
