# Generated by Django 5.1 on 2025-09-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_remove_client_bonus'),
        ('venues', '0040_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonushistory',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='venues.venue', verbose_name='Заведение'),
            preserve_default=False,
        ),
    ]
