# Generated by Django 5.1 on 2025-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_bonushistory_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заказ оформлен'), (1, 'Готовим заказ'), (2, 'Заказ готов'), (3, 'Заказ выполнен'), (4, 'Ожидает оплату'), (5, 'В доставке'), (7, 'Отменён')], default=4, verbose_name='Статус заказа'),
        ),
    ]
