# Generated by Django 5.1 on 2025-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('external_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID транзакции от платежного сервиса')),
                ('transaction_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу платежа')),
                ('pay_method', models.CharField(choices=[('cash', 'Наличные'), ('bakai_bank', 'Bakai Bank')], max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус оплаты')),
                ('json_data', models.JSONField(blank=True, null=True, verbose_name='Ответ из платежной системы')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
