# Generated by Django 5.1 on 2025-04-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
