# Generated by Django 5.1 on 2025-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
