# Generated by Django 5.1 on 2025-05-16 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_total_price'),
        ('venues', '0027_remove_spot_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('bakai', 'Bakai bank')], max_length=50)),
                ('name', models.CharField(blank=True, help_text='Название или описание аккаунта', max_length=100, null=True)),
                ('token', models.CharField(help_text='Секретный платёжный токен/API ключ', max_length=512)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='venues.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Платёжный аккаунт',
                'verbose_name_plural': 'Платёжные аккаунты',
            },
        ),
    ]
