# Generated by Django 5.1 on 2025-05-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_paymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='token',
            field=models.TextField(help_text='Секретный платёжный токен/API ключ'),
        ),
    ]
