# Generated by Django 5.1 on 2025-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_paymentaccount_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='service',
            field=models.CharField(choices=[('bakai', 'Bakai bank')], max_length=50, verbose_name='Сервис'),
        ),
    ]
